[2025-06-18T13:40:17.348+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-06-18T13:40:17.388+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: lakehouse_ingest_pipeline.produce_csv_to_kafka manual__2025-06-18T13:40:16.957463+00:00 [queued]>
[2025-06-18T13:40:17.396+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: lakehouse_ingest_pipeline.produce_csv_to_kafka manual__2025-06-18T13:40:16.957463+00:00 [queued]>
[2025-06-18T13:40:17.397+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-06-18T13:40:17.414+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): produce_csv_to_kafka> on 2025-06-18 13:40:16.957463+00:00
[2025-06-18T13:40:17.422+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=184) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-06-18T13:40:17.424+0000] {standard_task_runner.py:63} INFO - Started process 185 to run task
[2025-06-18T13:40:17.422+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'lakehouse_ingest_pipeline', 'produce_csv_to_kafka', 'manual__2025-06-18T13:40:16.957463+00:00', '--job-id', '2', '--raw', '--subdir', 'DAGS_FOLDER/lakehouse_ingest_pipeline.py', '--cfg-path', '/tmp/tmpoigpcbpa']
[2025-06-18T13:40:17.428+0000] {standard_task_runner.py:91} INFO - Job 2: Subtask produce_csv_to_kafka
[2025-06-18T13:40:17.444+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-06-18T13:40:17.487+0000] {task_command.py:426} INFO - Running <TaskInstance: lakehouse_ingest_pipeline.produce_csv_to_kafka manual__2025-06-18T13:40:16.957463+00:00 [running]> on host 1b5e61ed3f64
[2025-06-18T13:40:17.596+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='lakehouse_ingest_pipeline' AIRFLOW_CTX_TASK_ID='produce_csv_to_kafka' AIRFLOW_CTX_EXECUTION_DATE='2025-06-18T13:40:16.957463+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-18T13:40:16.957463+00:00'
[2025-06-18T13:40:17.598+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-06-18T13:40:17.637+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-06-18T13:40:17.639+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/tools/produce_csv_to_kafka.py --bootstrap-server localhost:9094 --topic footware_sales --file /opt/***/data/FootWare_Sales_Dataset/FootWare_Wholesale_Sales_Dataset.csv']
[2025-06-18T13:40:17.650+0000] {subprocess.py:86} INFO - Output:
[2025-06-18T13:40:17.790+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-06-18T13:40:17.791+0000] {subprocess.py:93} INFO -   File "/opt/***/tools/produce_csv_to_kafka.py", line 3, in <module>
[2025-06-18T13:40:17.794+0000] {subprocess.py:93} INFO -     from kafka import KafkaProducer
[2025-06-18T13:40:17.795+0000] {subprocess.py:93} INFO - ModuleNotFoundError: No module named 'kafka'
[2025-06-18T13:40:17.798+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-06-18T13:40:17.799+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-06-18T13:40:17.813+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-06-18T13:40:17.821+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=lakehouse_ingest_pipeline, task_id=produce_csv_to_kafka, run_id=manual__2025-06-18T13:40:16.957463+00:00, execution_date=20250618T134016, start_date=20250618T134017, end_date=20250618T134017
[2025-06-18T13:40:17.836+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 2 for task produce_csv_to_kafka (Bash command failed. The command returned a non-zero exit code 1.; 185)
[2025-06-18T13:40:17.880+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-06-18T13:40:17.908+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-06-18T13:40:17.910+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
